### ISSUE TITLE
elasticcache-cluster-config support for dotnet core 2.1

### ISSUE THREAD

**Issue by rajkumars82** [awslabs/elasticache-cluster-config-net#10] opened 2018-09-05 09:46 UTC
Hi - Support for dotnet core 2.1, currently no support available for library EnyimMemcachedCore 2.1.8
any update on this?

**Comment by klaytaybai** [comment] 2018-11-19 07:22
Hi @rajkumars82, I'm going to close this as a duplicate of #6, which you have already commented on, so we can track the discussion in one place.

**Closed as completed by klaytaybai** 2018-11-19 07:22 UTC
Labels: duplicate
